# Generated by Django 2.1.5 on 2019-01-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='presentor',
            new_name='presenter',
        ),
    ]
